apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
  namespace: feast
data:
  feature_store.yaml: |
    project: feast_project
    registry: file:///tmp/registry.db
    provider: local
    online_store:
      type: redis
      connection_string: feast-redis:6379
    offline_store:
      type: file 