apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-serving
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-serving
  template:
    metadata:
      labels:
        app: feast-serving
    spec:
      containers:
      - name: feast-serving
        image: feastdev/feast-server:0.34.1
        ports:
        - containerPort: 6566
          name: grpc
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: FEAST_FEATURE_STORE_CONFIG_PATH
          value: /app/feature_store.yaml
        volumeMounts:
        - name: feast-config
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: feast-config
        configMap:
          name: feast-config 