apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- redis-deployment.yaml
- redis-service.yaml
- feast-config.yaml
- feast-deployment.yaml
- feast-service.yaml
- features-configmap.yaml
- job-apply-features.yaml

namespace: feast 