apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-redis
  namespace: feast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feast-redis
  template:
    metadata:
      labels:
        app: feast-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {} 