apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feast
resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: feast-serving
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: docker.io/${DOCKERHUB_USERNAME}/feast-server:${GITHUB_SHA}
    - op: replace
      path: /spec/replicas
      value: 3

- target:
    kind: ConfigMap
    name: feast-config
  patch: |-
    - op: replace
      path: /data/feature_store.yaml
      value: |
        project: feast-project-production
        registry: file:///tmp/registry.db
        provider: local
        online_store:
          type: redis
          connection_string: feast-redis:6379
        offline_store:
          type: file