name: Feast CD Production Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/feast-server

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
          
      - name: Verify cluster connection
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes -o wide
          
      - name: Create Docker Hub pull secret
        run: |
          kubectl create secret docker-registry dockerhub-pull-secret \
            --docker-server=docker.io \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKERHUB_EMAIL }} \
            -n feast \
            --dry-run=client -o yaml | kubectl apply -f -
          
      - name: Deploy to production
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          cd infrastructure/kubernetes
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export GITHUB_SHA=${{ github.sha }}
          kustomize build overlays/production | envsubst | kubectl apply -f -
          
      - name: Verify deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/feast-serving -n feast
