name: Feast CD Staging Pipeline

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/feast-server

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    steps:
      - uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_STAGING }}
          
      - name: Deploy to staging
        run: |
          cd infrastructure/kubernetes
          kustomize build overlays/staging | kubectl apply -f -
          
      - name: Verify deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/feast-serving -n feast
