name: Feast CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/feast-server

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r feature-repo/requirements.txt
          pip install pytest mypy black isort
          
      - name: Validate feature definitions
        run: |
          cd feature-repo
          python -c "from feast import FeatureStore; FeatureStore('.').validate_feature_views()"
          
      - name: Run linting
        run: |
          black --check feature-repo
          isort --check feature-repo
          mypy feature-repo
          
      - name: Run unit tests
        run: |
          pytest tests/unit
          
  integration-test:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Kind Cluster
        uses: helm/kind-action@v1.5.0
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r feature-repo/requirements.txt
          pip install pytest
          
      - name: Deploy Feast to Kind
        run: |
          kubectl create namespace feast
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install feast-redis bitnami/redis --namespace feast
          kubectl apply -k infrastructure/kubernetes/overlays/staging
          
      - name: Wait for deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/feast-serving -n feast
          
      - name: Run integration tests
        run: |
          pytest tests/integration

  build:
    runs-on: ubuntu-latest
    needs: [validate]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
